-- AlterTable
ALTER TABLE `Information` MODIFY `content` VARCHAR(191) NULL,
    MODIFY `img` VARCHAR(191) NULL,
    MODIFY `video` VARCHAR(191) NULL,
    MODIFY `delete` BOOLEAN NULL DEFAULT false,
    MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updatedAt` DATETIME(3) NULL,
    MODIFY `type` VARCHAR(191) NULL DEFAULT '1';
